### ISSUE TITLE
Pas de licence

### ISSUE THREAD

**Issue by HunteRoi** [IESN-IG/da#2]
Ce projet n'a pas de licence. Par défaut, les lois de copyright s'appliquent donc. Cela signifie que personne n'est autorisé à reproduire, distribuer ou créer une oeuvre dérivée. Plus d'infos ici: [GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license).
Ainsi, que faire de ces forks? 
[![IMAGE](https://i.gyazo.com/56e8cde3e12f8407fa0bfd93e3efb5d1.png)](https://github.com/Section-IG/da/network/members)

Comment devrions-nous considérer cette application? Souhaites-tu garder tous les droits sur cette dernière ou veux-tu y ajouter une licence qui te semble correcte par rapport à sa présence au sein de cette organisation? @gaetanledocte

**Comment by gaetanledocte** [comment]
Quelle license proposes-tu pour satisfaire tout le monde ?

**Comment by HunteRoi** [comment]
Je ne veux pas t'influencer dans cette décision, ni imposer la mienne. C'est pourquoi je t'invite à regarder sur https://choosealicense.com/ afin de trouver la licence qui selon toi est la mieux adaptée à notre activité et à ton projet.

N'hésite pas à demander notre avis si tu doutes ou ne sais pas choisir entre plusieurs licences.

**Comment by gaetanledocte** [comment]
@HunteRoi J'ai choisi d'intégrer une licence MIT qui me semble adaptée pour un projet comme celui-ci. Je propose de fermer l'issue si tout est bon. Merci ! :)

**Comment by HunteRoi** [comment]
Parfait!
